pipeline {
	agent any
		stages {
			stage('Clean stage') {
				steps {
					dir("MiscTopicsDemo") {
						bat '"C:/Program Files/apache-maven-3.8.4/bin/mvn" clean'
					}
				}
			}
			stage('Compile stage') {
				steps {
					dir("MiscTopicsDemo") {
						bat '"C:/Program Files/apache-maven-3.8.4/bin/mvn" compile'
					}
				}
			}
			stage('Install stage') {
				steps {
					dir("MiscTopicsDemo") {
						bat '"C:/Program Files/apache-maven-3.8.4/bin/mvn" install'
					}
				}
			}
		}
}